AI_U  = 1
AI_RU = 2
AI_R  = 3
AI_RD = 4
AI_D  = 5
AI_LD = 6
AI_L  = 7
AI_LU = 8

AI_ATTACK_POWERTHROW = 9
AI_ATTACK_STUN = 10
AI_DEFEND_BARRIER = 9
AI_DEFEND_MASK = 10

AI_THROWBALL = 11
AI_MODECHANGE = 12
AI_SKILLCARD_HIDE = 13 # invisible
AI_SKILLCARD_DEMENTOR = 14 # empty power
AI_SKILLCARD_STUNALL = 15 # stun all enermy
AI_SKILLCARD_SPECIAL = 16
AI_CALLME = 17